apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-depl
  labels:
    app: comment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment
  template:
    metadata:
      labels:
        app: comment
    spec:
      containers:
        - name: comment
          image: node-service/comment:0.0.2
