apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-depl
  labels:
    app: post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: node-service/post:0.0.1
