apiVersion: v1
kind: Service
metadata:
  name: client-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 3000
      protocol: TCP
      targetPort: 3000
