apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl
  labels:
    app: event-bus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus
          image: erfanrider/event-bus
