apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-depl
  labels:
    app: moderation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation
  template:
    metadata:
      labels:
        app: moderation
    spec:
      containers:
        - name: moderation
          image: erfanrider/moderation
