apiVersion: v1
kind: Service
metadata:
  name: query-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: query
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 5002
      protocol: TCP
      targetPort: 5002

---
apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  type: NodePort
  selector:
    app: query
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 5002
      protocol: TCP
      targetPort: 5002
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30009
